-- This file is generated by ex-colors. The credit goes to the authors and contributors of the original colorscheme catppuccin-mocha.
vim.api.nvim_set_var('colors_name', 'ex-catppuccin-mocha')
vim.api.nvim_set_hl(0, '@attribute', { link = 'Constant' })
vim.api.nvim_set_hl(0, '@comment.documentation', { link = 'Comment' })
vim.api.nvim_set_hl(0, '@comment.error', { bg = 15961000, fg = 1973806 })
vim.api.nvim_set_hl(0, '@comment.note', { bg = 9024762, fg = 1973806 })
vim.api.nvim_set_hl(0, '@comment.todo', { bg = 15912397, fg = 1973806 })
vim.api.nvim_set_hl(0, '@comment.warning', { bg = 16376495, fg = 1973806 })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = 16429959 })
vim.api.nvim_set_hl(0, '@constant.macro', { link = 'Macro' })
vim.api.nvim_set_hl(0, '@constructor', { fg = 7653356 })
vim.api.nvim_set_hl(0, '@diff.delta', { link = 'diffChanged' })
vim.api.nvim_set_hl(0, '@diff.minus', { link = 'diffRemoved' })
vim.api.nvim_set_hl(0, '@diff.plus', { link = 'diffAdded' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = 16429959 })
vim.api.nvim_set_hl(0, '@function.call', { link = 'Function' })
vim.api.nvim_set_hl(0, '@function.macro', { fg = 9757397 })
vim.api.nvim_set_hl(0, '@function.method', { link = 'Function' })
vim.api.nvim_set_hl(0, '@function.method.call', { link = 'Function' })
vim.api.nvim_set_hl(0, '@keyword.conditional', { link = 'Conditional' })
vim.api.nvim_set_hl(0, '@keyword.conditional.ternary', { link = 'Operator' })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { link = 'Keyword' })
vim.api.nvim_set_hl(0, '@keyword.debug', { link = 'Exception' })
vim.api.nvim_set_hl(0, '@keyword.directive', { link = 'PreProc' })
vim.api.nvim_set_hl(0, '@keyword.directive.define', { link = 'Define' })
vim.api.nvim_set_hl(0, '@keyword.exception', { link = 'Exception' })
vim.api.nvim_set_hl(0, '@keyword.function', { fg = 13346551 })
vim.api.nvim_set_hl(0, '@keyword.import', { link = 'Include' })
vim.api.nvim_set_hl(0, '@keyword.modifier', { link = 'Keyword' })
vim.api.nvim_set_hl(0, '@keyword.operator', { link = 'Operator' })
vim.api.nvim_set_hl(0, '@keyword.repeat', { link = 'Repeat' })
vim.api.nvim_set_hl(0, '@keyword.return', { fg = 13346551 })
vim.api.nvim_set_hl(0, '@keyword.type', { link = 'Keyword' })
vim.api.nvim_set_hl(0, '@lsp.type.interface', { fg = 15912397 })
vim.api.nvim_set_hl(
  0,
  '@markup.heading',
  { bold = true, cterm = { bold = true }, fg = 9024762 }
)
vim.api.nvim_set_hl(
  0,
  '@markup.italic',
  { cterm = { italic = true }, fg = 15442092, italic = true }
)
vim.api.nvim_set_hl(0, '@markup.link', { link = 'Tag' })
vim.api.nvim_set_hl(0, '@markup.link.label', { link = 'Label' })
vim.api.nvim_set_hl(0, '@markup.link.url', {
  cterm = { italic = true, underline = true },
  fg = 16113884,
  italic = true,
  underline = true,
})
vim.api.nvim_set_hl(0, '@markup.list', { link = 'Special' })
vim.api.nvim_set_hl(0, '@markup.list.checked', { fg = 10937249 })
vim.api.nvim_set_hl(0, '@markup.list.unchecked', { fg = 8357020 })
vim.api.nvim_set_hl(0, '@markup.math', { fg = 9024762 })
vim.api.nvim_set_hl(
  0,
  '@markup.quote',
  { bold = true, cterm = { bold = true }, fg = 15442092 }
)
vim.api.nvim_set_hl(0, '@markup.raw', { fg = 9757397 })
vim.api.nvim_set_hl(
  0,
  '@markup.strikethrough',
  { cterm = { strikethrough = true }, fg = 13489908, strikethrough = true }
)
vim.api.nvim_set_hl(
  0,
  '@markup.strong',
  { bold = true, cterm = { bold = true }, fg = 15442092 }
)
vim.api.nvim_set_hl(0, '@markup.underline', { link = 'Underlined' })
vim.api.nvim_set_hl(
  0,
  '@module',
  { cterm = { italic = true }, fg = 11845374, italic = true }
)
vim.api.nvim_set_hl(0, '@property', { fg = 11845374 })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = 9673138 })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { link = 'Delimiter' })
vim.api.nvim_set_hl(0, '@string.documentation', { fg = 9757397 })
vim.api.nvim_set_hl(0, '@string.escape', { fg = 16106215 })
vim.api.nvim_set_hl(0, '@string.regexp', { fg = 16429959 })
vim.api.nvim_set_hl(0, '@string.special', { link = 'Special' })
vim.api.nvim_set_hl(0, '@string.special.path', { link = 'Special' })
vim.api.nvim_set_hl(0, '@string.special.symbol', { fg = 15912397 })
vim.api.nvim_set_hl(0, '@string.special.url', {
  cterm = { italic = true, underline = true },
  fg = 16113884,
  italic = true,
  underline = true,
})
vim.api.nvim_set_hl(0, '@tag', { fg = 13346551 })
vim.api.nvim_set_hl(
  0,
  '@tag.attribute',
  { cterm = { italic = true }, fg = 9757397, italic = true }
)
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = 9034987 })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = 16376495 })
vim.api.nvim_set_hl(0, '@type.definition', { link = 'Type' })
vim.api.nvim_set_hl(0, '@variable', { fg = 13489908 })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = 15961000 })
vim.api.nvim_set_hl(0, '@variable.member', { fg = 11845374 })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = 15442092 })
vim.api.nvim_set_hl(0, 'Boolean', { fg = 16429959 })
vim.api.nvim_set_hl(0, 'Character', { fg = 9757397 })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = 3224132 })
vim.api.nvim_set_hl(
  0,
  'Comment',
  { cterm = { italic = true }, fg = 9673138, italic = true }
)
vim.api.nvim_set_hl(0, 'Conceal', { fg = 8357020 })
vim.api.nvim_set_hl(
  0,
  'Conditional',
  { cterm = { italic = true }, fg = 13346551, italic = true }
)
vim.api.nvim_set_hl(0, 'Constant', { fg = 16429959 })
vim.api.nvim_set_hl(0, 'CurSearch', { bg = 15961000, fg = 1579045 })
vim.api.nvim_set_hl(0, 'Cursor', { bg = 13489908, fg = 1973806 })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = 1579045 })
vim.api.nvim_set_hl(0, 'CursorIM', { bg = 13489908, fg = 1973806 })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = 2763580 })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = 11845374 })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = 9673138 })
vim.api.nvim_set_hl(
  0,
  'DiagnosticError',
  { cterm = { italic = true }, fg = 15961000, italic = true }
)
vim.api.nvim_set_hl(0, 'DiagnosticFloatingError', { fg = 15961000 })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingHint', { fg = 9757397 })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingInfo', { fg = 9034987 })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingOk', { fg = 10937249 })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingWarn', { fg = 16376495 })
vim.api.nvim_set_hl(
  0,
  'DiagnosticHint',
  { cterm = { italic = true }, fg = 9757397, italic = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticInfo',
  { cterm = { italic = true }, fg = 9034987, italic = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticOk',
  { cterm = { italic = true }, fg = 10937249, italic = true }
)
vim.api.nvim_set_hl(0, 'DiagnosticSignError', { fg = 15961000 })
vim.api.nvim_set_hl(0, 'DiagnosticSignHint', { fg = 9757397 })
vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', { fg = 9034987 })
vim.api.nvim_set_hl(0, 'DiagnosticSignOk', { fg = 10937249 })
vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', { fg = 16376495 })
vim.api.nvim_set_hl(
  0,
  'DiagnosticUnderlineError',
  { cterm = { underline = true }, sp = 15961000, underline = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticUnderlineHint',
  { cterm = { underline = true }, sp = 9757397, underline = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticUnderlineInfo',
  { cterm = { underline = true }, sp = 9034987, underline = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticUnderlineOk',
  { cterm = { underline = true }, sp = 10937249, underline = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticUnderlineWarn',
  { cterm = { underline = true }, sp = 16376495, underline = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticVirtualTextError',
  { bg = 3287098, cterm = { italic = true }, fg = 15961000, italic = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticVirtualTextHint',
  { bg = 2699582, cterm = { italic = true }, fg = 9757397, italic = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticVirtualTextInfo',
  { bg = 2633792, cterm = { italic = true }, fg = 9034987, italic = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticVirtualTextOk',
  { bg = 2699582, cterm = { italic = true }, fg = 10937249, italic = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticVirtualTextWarn',
  { bg = 3354938, cterm = { italic = true }, fg = 16376495, italic = true }
)
vim.api.nvim_set_hl(
  0,
  'DiagnosticWarn',
  { cterm = { italic = true }, fg = 16376495, italic = true }
)
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = 3555651 })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = 2435388 })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = 4469316 })
vim.api.nvim_set_hl(0, 'DiffText', { bg = 4082539 })
vim.api.nvim_set_hl(0, 'Directory', { fg = 9024762 })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = 1973806 })
vim.api.nvim_set_hl(0, 'Error', { fg = 15961000 })
vim.api.nvim_set_hl(
  0,
  'ErrorMsg',
  {
    bold = true,
    cterm = { bold = true, italic = true },
    fg = 15961000,
    italic = true,
  }
)
vim.api.nvim_set_hl(0, 'Exception', { fg = 13346551 })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = 9024762 })
vim.api.nvim_set_hl(0, 'FloatTitle', { fg = 10923464 })
vim.api.nvim_set_hl(0, 'FoldColumn', { fg = 7106694 })
vim.api.nvim_set_hl(0, 'Folded', { bg = 4540250, fg = 9024762 })
vim.api.nvim_set_hl(0, 'Function', { fg = 9024762 })
vim.api.nvim_set_hl(0, 'Identifier', { fg = 15912397 })
vim.api.nvim_set_hl(0, 'IncSearch', { bg = 8309208, fg = 1579045 })
vim.api.nvim_set_hl(0, 'Include', { fg = 13346551 })
vim.api.nvim_set_hl(0, 'Keyword', { fg = 13346551 })
vim.api.nvim_set_hl(0, 'Label', { fg = 7653356 })
vim.api.nvim_set_hl(0, 'LineNr', { fg = 4540250 })
vim.api.nvim_set_hl(0, 'LspCodeLens', { fg = 7106694 })
vim.api.nvim_set_hl(0, 'LspInlayHint', { bg = 2763580, fg = 7106694 })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = 4540250 })
vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = 4540250 })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = 4540250 })
vim.api.nvim_set_hl(
  0,
  'LspSignatureActiveParameter',
  { bg = 3224132, bold = true, cterm = { bold = true } }
)
vim.api.nvim_set_hl(0, 'Macro', { fg = 13346551 })
vim.api.nvim_set_hl(
  0,
  'MatchParen',
  { bg = 4540250, bold = true, cterm = { bold = true }, fg = 16429959 }
)
vim.api.nvim_set_hl(
  0,
  'ModeMsg',
  { bold = true, cterm = { bold = true }, fg = 13489908 }
)
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = 9024762 })
vim.api.nvim_set_hl(0, 'NonText', { fg = 7106694 })
vim.api.nvim_set_hl(0, 'Normal', { bg = 1973806, fg = 13489908 })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 1579045, fg = 13489908 })
vim.api.nvim_set_hl(0, 'NormalNC', { bg = 1973806, fg = 13489908 })
vim.api.nvim_set_hl(0, 'Number', { fg = 16429959 })
vim.api.nvim_set_hl(0, 'Operator', { fg = 9034987 })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = 2829116, fg = 9673138 })
vim.api.nvim_set_hl(0, 'PmenuMatch', { bold = true, cterm = { bold = true } })
vim.api.nvim_set_hl(
  0,
  'PmenuMatchSel',
  { bold = true, cterm = { bold = true } }
)
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = 4540250 })
vim.api.nvim_set_hl(
  0,
  'PmenuSel',
  { bg = 4540250, bold = true, cterm = { bold = true } }
)
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = 7106694 })
vim.api.nvim_set_hl(0, 'PreProc', { fg = 16106215 })
vim.api.nvim_set_hl(0, 'Question', { fg = 9024762 })
vim.api.nvim_set_hl(
  0,
  'QuickFixLine',
  { bg = 4540250, bold = true, cterm = { bold = true } }
)
vim.api.nvim_set_hl(0, 'Repeat', { fg = 13346551 })
vim.api.nvim_set_hl(0, 'Search', { bg = 4085607, fg = 13489908 })
vim.api.nvim_set_hl(0, 'SignColumn', { fg = 4540250 })
vim.api.nvim_set_hl(0, 'Special', { fg = 16106215 })
vim.api.nvim_set_hl(0, 'SpecialKey', { link = 'NonText' })
vim.api.nvim_set_hl(
  0,
  'SpellBad',
  { cterm = { undercurl = true }, sp = 15961000, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  'SpellCap',
  { cterm = { undercurl = true }, sp = 16376495, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  'SpellLocal',
  { cterm = { undercurl = true }, sp = 9024762, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  'SpellRare',
  { cterm = { undercurl = true }, sp = 10937249, undercurl = true }
)
vim.api.nvim_set_hl(0, 'Statement', { fg = 13346551 })
vim.api.nvim_set_hl(0, 'StatusLine', { bg = 1579045, fg = 13489908 })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = 1579045, fg = 4540250 })
vim.api.nvim_set_hl(0, 'StatusLineTerm', { link = 'StatusLine' })
vim.api.nvim_set_hl(0, 'StatusLineTermNC', { link = 'StatusLineNC' })
vim.api.nvim_set_hl(0, 'StorageClass', { fg = 16376495 })
vim.api.nvim_set_hl(0, 'String', { fg = 10937249 })
vim.api.nvim_set_hl(0, 'Structure', { fg = 16376495 })
vim.api.nvim_set_hl(0, 'Substitute', { bg = 4540250, fg = 16106215 })
vim.api.nvim_set_hl(0, 'TabLine', { bg = 1118491, fg = 7106694 })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = 1579045 })
vim.api.nvim_set_hl(0, 'TabLineSel', { link = 'Normal' })
vim.api.nvim_set_hl(
  0,
  'Tag',
  { bold = true, cterm = { bold = true }, fg = 11845374 }
)
vim.api.nvim_set_hl(0, 'TermCursor', { bg = 16113884, fg = 1973806 })
vim.api.nvim_set_hl(
  0,
  'Title',
  { bold = true, cterm = { bold = true }, fg = 9024762 }
)
vim.api.nvim_set_hl(
  0,
  'Todo',
  { bg = 15912397, bold = true, cterm = { bold = true }, fg = 1973806 }
)
vim.api.nvim_set_hl(0, 'Type', { fg = 16376495 })
vim.api.nvim_set_hl(
  0,
  'Visual',
  { bg = 4540250, bold = true, cterm = { bold = true } }
)
vim.api.nvim_set_hl(
  0,
  'VisualNOS',
  { bg = 4540250, bold = true, cterm = { bold = true } }
)
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = 16376495 })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = 4540250 })
vim.api.nvim_set_hl(0, 'WildMenu', { bg = 7106694 })
vim.api.nvim_set_hl(0, 'WinBar', { fg = 16113884 })
vim.api.nvim_set_hl(0, 'WinBarNC', { link = 'WinBar' })
vim.api.nvim_set_hl(0, 'WinSeparator', { fg = 1118491 })
vim.api.nvim_set_hl(0, 'diffAdded', { fg = 10937249 })
vim.api.nvim_set_hl(0, 'diffChanged', { fg = 9024762 })
vim.api.nvim_set_hl(0, 'diffFile', { fg = 9024762 })
vim.api.nvim_set_hl(0, 'diffIndexLine', { fg = 9757397 })
vim.api.nvim_set_hl(0, 'diffLine', { fg = 7106694 })
vim.api.nvim_set_hl(0, 'diffNewFile', { fg = 16429959 })
vim.api.nvim_set_hl(0, 'diffOldFile', { fg = 16376495 })
vim.api.nvim_set_hl(0, 'diffRemoved', { fg = 15961000 })
vim.api.nvim_set_hl(
  0,
  'htmlH1',
  { bold = true, cterm = { bold = true }, fg = 16106215 }
)
vim.api.nvim_set_hl(
  0,
  'htmlH2',
  { bold = true, cterm = { bold = true }, fg = 9024762 }
)
vim.api.nvim_set_hl(0, 'lCursor', { bg = 13489908, fg = 1973806 })
vim.api.nvim_set_hl(0, 'markdownH1', { link = 'rainbow1' })
vim.api.nvim_set_hl(0, 'markdownH2', { link = 'rainbow2' })
vim.api.nvim_set_hl(0, 'markdownH3', { link = 'rainbow3' })
vim.api.nvim_set_hl(0, 'markdownH4', { link = 'rainbow4' })
vim.api.nvim_set_hl(0, 'markdownH5', { link = 'rainbow5' })
vim.api.nvim_set_hl(0, 'markdownH6', { link = 'rainbow6' })
vim.api.nvim_set_hl(0, 'rainbow1', { fg = 15961000 })
vim.api.nvim_set_hl(0, 'rainbow2', { fg = 16429959 })
vim.api.nvim_set_hl(0, 'rainbow3', { fg = 16376495 })
vim.api.nvim_set_hl(0, 'rainbow4', { fg = 10937249 })
vim.api.nvim_set_hl(0, 'rainbow5', { fg = 7653356 })
vim.api.nvim_set_hl(0, 'rainbow6', { fg = 11845374 })
